name = "Hackbox Modpack"
author = "sharpsyd"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b4d94226faa2d1ec306a3336286fdf19f413edb1339adfe407249bc76734ada0"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
